'use server';

import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';

export interface InviteEntry {
  email: string;
  role: 'analyst' | 'admin' | 'viewer';
}

export interface OnboardingWeights {
  vuln: number;
  config: number;
  access: number;
  network: number;
  compliance: number;
  incident: number;
}

export interface OnboardingData {
  orgId: string;
  description: string;
  contactEmail: string;
  website: string;
  objectTypes: string[];
  weights: OnboardingWeights;
  invites: InviteEntry[];
}

export async function completeOnboarding(data: OnboardingData) {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect('/login');

  // Update trust factor config weights
  await supabase
    .from('trust_factor_config')
    .update({
      vuln_weight: data.weights.vuln,
      config_weight: data.weights.config,
      access_weight: data.weights.access,
      network_weight: data.weights.network,
      compliance_weight: data.weights.compliance,
      incident_weight: data.weights.incident,
    } as never)
    .eq('organization_id', data.orgId);

  // Create invitations (token generated by DB default)
  if (data.invites.length > 0) {
    const validInvites = data.invites.filter((inv) => inv.email.includes('@'));
    if (validInvites.length > 0) {
      await supabase.from('invitations').insert(
        validInvites.map((inv) => ({
          organization_id: data.orgId,
          email: inv.email,
          role: inv.role,
          invited_by: user.id,
        })) as never,
      );
    }
  }

  redirect('/dashboard');
}
