'use server';

import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { getCurrentUserContext } from '@/lib/supabase/auth';

export interface InviteEntry {
  email: string;
  role: 'analyst' | 'admin' | 'viewer';
}

export interface OnboardingWeights {
  vuln: number;
  config: number;
  access: number;
  network: number;
  compliance: number;
  incident: number;
}

export interface OnboardingData {
  orgId: string;
  description: string;
  contactEmail: string;
  website: string;
  objectTypes: string[];
  weights: OnboardingWeights;
  invites: InviteEntry[];
}

export async function completeOnboarding(data: OnboardingData) {
  const context = await getCurrentUserContext();
  if (!context) redirect('/login');
  const supabase = await createClient();

  // Update trust factor config weights
  const weightsResult = supabase
    .from('trust_factor_config')
    .update({
      vuln_weight: data.weights.vuln,
      config_weight: data.weights.config,
      access_weight: data.weights.access,
      network_weight: data.weights.network,
      compliance_weight: data.weights.compliance,
      incident_weight: data.weights.incident,
    } as never)
    .eq('organization_id', data.orgId);

  // Create invitations (token generated by DB default)
  let invitationsResult: PromiseLike<{ error: unknown }> | null = null;
  if (data.invites.length > 0) {
    const validInvites = data.invites.filter((inv) => inv.email.includes('@'));
    if (validInvites.length > 0) {
      invitationsResult = supabase.from('invitations').insert(
        validInvites.map((inv) => ({
          organization_id: data.orgId,
          email: inv.email,
          role: inv.role,
          invited_by: context.userId,
        })) as never,
      );
    }
  }

  const [weightsResponse, invitationsResponse] = await Promise.all([
    weightsResult,
    invitationsResult,
  ]);
  if (weightsResponse.error || invitationsResponse?.error) {
    return { error: 'Не удалось завершить настройку. Попробуйте ещё раз.' };
  }

  redirect('/dashboard');
}
